detector: YOLOV3

YOLOV3:
  backbone: ResNet50
  encoder: FPNEncoder
  decoder: YOLOV3Decoder
  target: YOLOV3Target

ResNet50:
  norm_type: bn
  activation: relu

FPNEncoder:
  norm_type: bn

YOLOV3Decoder:
  norm_type: bn

YOLOV3Target:
  norm_type: bn


